### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by JigneshChowdary** [xuekt98/BBDM#13]
str(Exception):  <class 'Exception'>
str(e):          'Namespace' object has no attribute 'accumulate_grad_batches'
repr(e):         AttributeError("'Namespace' object has no attribute 'accumulate_grad_batches'")
traceback.print_exc():
Traceback (most recent call last):
  File "/data/home/stufs1/jgutta/BBDM/runners/BaseRunner.py", line 376, in train
    accumulate_grad_batches = self.config.training.accumulate_grad_batches
AttributeError: 'Namespace' object has no attribute 'accumulate_grad_batches'
traceback.format_exc():
Traceback (most recent call last):
  File "/data/home/stufs1/jgutta/BBDM/runners/BaseRunner.py", line 376, in train
    accumulate_grad_batches = self.config.training.accumulate_grad_batches
AttributeError: 'Namespace' object has no attribute 'accumulate_grad_batches'

**Comment by hjlim-morai** [comment]
same error here, when training with configs/Template-BBDM.yaml

**Comment by egshkim** [comment]
Have same issue. have you solved it?

**Comment by xuekt98** [comment]
please add  "accumulate_grad_batches: number"  into the "training" options in your config.yaml
This option is used while GPU memory is not sufficient for  large batch size, and the grads will be accumulated for "number" steps before updating the parameters. 

training:
  accumulate_grad_batches: 1
