### ISSUE TITLE
Train problem

### ISSUE THREAD

**Issue by zhangbaijin** [xuekt98/BBDM#4]
Thanks for your code, i am trying train the code, and my dataset is  ./data/Semi/train/, ./data/Semi/val, ./data/Semi/test, and i set the config in the config.yaml, there is problem when i run the code: `    if self.config.model.only_load_latent_mean_std:
AttributeError: 'Namespace' object has no attribute 'only_load_latent_mean_std` 
Thanks for your help~

**Comment by hanzh346** [comment]
Hello,

I can probably compensate a bit here as I encountered the same issue:

create output path results/low_dose_PET/BrownianBridge/
Total Number of parameter: 237.09M
Trainable Number of parameter: 237.09M
Traceback (most recent call last):
  File "/home/hang/GitHub/BBDM/main.py", line 130, in <module>
    main()
  File "/home/hang/GitHub/BBDM/main.py", line 125, in main
    CPU_singleGPU_launcher(nconfig)
  File "/home/hang/GitHub/BBDM/main.py", line 91, in CPU_singleGPU_launcher
    runner = get_runner(config.runner, config)
  File "/home/hang/GitHub/BBDM/utils.py", line 45, in get_runner
    runner = Registers.runners[runner_name](config)
  File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 19, in __init__
    super().__init__(config)
  File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/DiffusionBaseRunner.py", line 11, in __init__
    super().__init__(config)
  File "/home/hang/GitHub/BBDM/runners/BaseRunner.py", line 66, in __init__
    self.load_model_from_checkpoint()
  File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 33, in load_model_from_checkpoint
    if self.config.model.only_load_latent_mean_std:
AttributeError: 'Namespace' object has no attribute 'only_load_latent_mean_std'

This happened when I run python3 main.py --config configs/Template-BBDM.yaml --train  --gpu_ids 0

> Thank you for your attention. Could you show the information in detail? Better using screenshot.

**Comment by hanzh346** [comment]
> Hello,
> 
> I can probably compensate a bit here as I encountered the same issue:
> 
> create output path results/low_dose_PET/BrownianBridge/ Total Number of parameter: 237.09M Trainable Number of parameter: 237.09M Traceback (most recent call last): File "/home/hang/GitHub/BBDM/main.py", line 130, in main() File "/home/hang/GitHub/BBDM/main.py", line 125, in main CPU_singleGPU_launcher(nconfig) File "/home/hang/GitHub/BBDM/main.py", line 91, in CPU_singleGPU_launcher runner = get_runner(config.runner, config) File "/home/hang/GitHub/BBDM/utils.py", line 45, in get_runner runner = Registers.runners[runner_name](config) File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 19, in **init** super().**init**(config) File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/DiffusionBaseRunner.py", line 11, in **init** super().**init**(config) File "/home/hang/GitHub/BBDM/runners/BaseRunner.py", line 66, in **init** self.load_model_from_checkpoint() File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 33, in load_model_from_checkpoint if self.config.model.only_load_latent_mean_std: AttributeError: 'Namespace' object has no attribute 'only_load_latent_mean_std'
> 
> This happened when I run python3 main.py --config configs/Template-BBDM.yaml --train --gpu_ids 0
> 
> > Thank you for your attention. Could you show the information in detail? Better using screenshot.

I overcome this issue by adding:   
  latent_before_quant_conv: False
  normalize_latent: False
  only_load_latent_mean_std: False
into the Template-BBDM.yaml file, under model section.

I think it is just in the old Template-BBDM.yaml, those parameters are not specified

**Comment by zhangbaijin** [comment]
Thanks a lot~

**Comment by yunfei920406** [comment]
> > Hello,
> > I can probably compensate a bit here as I encountered the same issue:
> > create output path results/low_dose_PET/BrownianBridge/ Total Number of parameter: 237.09M Trainable Number of parameter: 237.09M Traceback (most recent call last): File "/home/hang/GitHub/BBDM/main.py", line 130, in main() File "/home/hang/GitHub/BBDM/main.py", line 125, in main CPU_singleGPU_launcher(nconfig) File "/home/hang/GitHub/BBDM/main.py", line 91, in CPU_singleGPU_launcher runner = get_runner(config.runner, config) File "/home/hang/GitHub/BBDM/utils.py", line 45, in get_runner runner = Registers.runners[runner_name](config) File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 19, in **init** super().**init**(config) File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/DiffusionBaseRunner.py", line 11, in **init** super().**init**(config) File "/home/hang/GitHub/BBDM/runners/BaseRunner.py", line 66, in **init** self.load_model_from_checkpoint() File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 33, in load_model_from_checkpoint if self.config.model.only_load_latent_mean_std: AttributeError: 'Namespace' object has no attribute 'only_load_latent_mean_std'
> > This happened when I run python3 main.py --config configs/Template-BBDM.yaml --train --gpu_ids 0
> > > Thank you for your attention. Could you show the information in detail? Better using screenshot.
> 
> I overcome this issue by adding: latent_before_quant_conv: False normalize_latent: False only_load_latent_mean_std: False into the Template-BBDM.yaml file, under model section.
> 
> I think it is just in the old Template-BBDM.yaml, those parameters are not specified

I Met some errors! 
How did you define the "resume_model "in the *****.sh file for train if you just use your own dataset

**Comment by xuekt98** [comment]
> > > Hello,
> > > I can probably compensate a bit here as I encountered the same issue:
> > > create output path results/low_dose_PET/BrownianBridge/ Total Number of parameter: 237.09M Trainable Number of parameter: 237.09M Traceback (most recent call last): File "/home/hang/GitHub/BBDM/main.py", line 130, in main() File "/home/hang/GitHub/BBDM/main.py", line 125, in main CPU_singleGPU_launcher(nconfig) File "/home/hang/GitHub/BBDM/main.py", line 91, in CPU_singleGPU_launcher runner = get_runner(config.runner, config) File "/home/hang/GitHub/BBDM/utils.py", line 45, in get_runner runner = Registers.runners[runner_name](config) File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 19, in **init** super().**init**(config) File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/DiffusionBaseRunner.py", line 11, in **init** super().**init**(config) File "/home/hang/GitHub/BBDM/runners/BaseRunner.py", line 66, in **init** self.load_model_from_checkpoint() File "/home/hang/GitHub/BBDM/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 33, in load_model_from_checkpoint if self.config.model.only_load_latent_mean_std: AttributeError: 'Namespace' object has no attribute 'only_load_latent_mean_std'
> > > This happened when I run python3 main.py --config configs/Template-BBDM.yaml --train --gpu_ids 0
> > > > Thank you for your attention. Could you show the information in detail? Better using screenshot.
> > 
> > 
> > I overcome this issue by adding: latent_before_quant_conv: False normalize_latent: False only_load_latent_mean_std: False into the Template-BBDM.yaml file, under model section.
> > I think it is just in the old Template-BBDM.yaml, those parameters are not specified
> 
> I Met some errors! How did you define the "resume_model "in the *****.sh file for train if you just use your own dataset

just leave this option as default
