### ISSUE TITLE
Some Errors Apperas 

### ISSUE THREAD

**Issue by yunfei920406** [xuekt98/BBDM#6]
When I tried the command as follows: 

python3 main.py --config configs/Template-BBDM.yaml --train --sample_at_start --save_top --gpu_ids 0 --resume_model path/to/model_ckpt --resume_optim path/to/optim_ckpt

the error is: 

create output path results/dataset_name/BrownianBridge/
Total Number of parameter: 237.09M
Trainable Number of parameter: 237.09M
Traceback (most recent call last):
  File "/home/yunfei_zhang/BBDM-main/main.py", line 130, in <module>
    main()
  File "/home/yunfei_zhang/BBDM-main/main.py", line 125, in main
    CPU_singleGPU_launcher(nconfig)
  File "/home/yunfei_zhang/BBDM-main/main.py", line 91, in CPU_singleGPU_launcher
    runner = get_runner(config.runner, config)
  File "/home/yunfei_zhang/BBDM-main/utils.py", line 45, in get_runner
    runner = Registers.runners[runner_name](config)
  File "/home/yunfei_zhang/BBDM-main/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 19, in __init__
    super().__init__(config)
  File "/home/yunfei_zhang/BBDM-main/runners/DiffusionBasedModelRunners/DiffusionBaseRunner.py", line 11, in __init__
    super().__init__(config)
  File "/home/yunfei_zhang/BBDM-main/runners/BaseRunner.py", line 66, in __init__
    self.load_model_from_checkpoint()
  File "/home/yunfei_zhang/BBDM-main/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 33, in load_model_from_checkpoint
    if self.config.model.only_load_latent_mean_std:
AttributeError: 'Namespace' object has no attribute 'only_load_latent_mean_std'

**Comment by yunfei920406** [comment]
When I tried with  python3 main.py --config configs/Template_LBBDM_f4.yaml --train --sample_at_start --save_top --gpu_ids 0 --resume_model path/to/model_ckpt --resume_optim path/to/optim_ckpt

the error report is :

Traceback (most recent call last):
  File "/home/yunfei_zhang/BBDM-main/main.py", line 130, in <module>
    main()
  File "/home/yunfei_zhang/BBDM-main/main.py", line 125, in main
    CPU_singleGPU_launcher(nconfig)
  File "/home/yunfei_zhang/BBDM-main/main.py", line 91, in CPU_singleGPU_launcher
    runner = get_runner(config.runner, config)
  File "/home/yunfei_zhang/BBDM-main/utils.py", line 45, in get_runner
    runner = Registers.runners[runner_name](config)
  File "/home/yunfei_zhang/BBDM-main/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 19, in __init__
    super().__init__(config)
  File "/home/yunfei_zhang/BBDM-main/runners/DiffusionBasedModelRunners/DiffusionBaseRunner.py", line 11, in __init__
    super().__init__(config)
  File "/home/yunfei_zhang/BBDM-main/runners/BaseRunner.py", line 53, in __init__
    self.net, self.optimizer, self.scheduler = self.initialize_model_optimizer_scheduler(self.config)
  File "/home/yunfei_zhang/BBDM-main/runners/BaseRunner.py", line 92, in initialize_model_optimizer_scheduler
    net = self.initialize_model(config)
  File "/home/yunfei_zhang/BBDM-main/runners/DiffusionBasedModelRunners/BBDMRunner.py", line 25, in initialize_model
    bbdmnet = LatentBrownianBridgeModel(config.model).to(config.training.device[0])
  File "/home/yunfei_zhang/BBDM-main/model/BrownianBridge/LatentBrownianBridgeModel.py", line 23, in __init__
    self.vqgan = VQModel(**vars(model_config.VQGAN.params)).eval()
  File "/home/yunfei_zhang/BBDM-main/model/VQGAN/vqgan.py", line 55, in __init__
    self.init_from_ckpt(ckpt_path, ignore_keys=ignore_keys)
  File "/home/yunfei_zhang/BBDM-main/model/VQGAN/vqgan.py", line 64, in init_from_ckpt
    sd = torch.load(path, map_location="cpu")["state_dict"]
  File "/home/yunfei_zhang/anaconda3/envs/BBDM/lib/python3.9/site-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/yunfei_zhang/anaconda3/envs/BBDM/lib/python3.9/site-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/yunfei_zhang/anaconda3/envs/BBDM/lib/python3.9/site-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'results/VQGAN/CelebAMaskHQ-f4.ckpt'

**Comment by yunfei920406** [comment]
> 
Can you show more details about how to prepare the checkpoint file of VQGAN for may own dataset.

**Comment by xuekt98** [comment]
The pre-trained VQGAN models provided by LDM can be directly used for all tasks.
https://github.com/CompVis/latent-diffusion#bibtex

**Comment by xuekt98** [comment]
https://ommer-lab.com/files/latent-diffusion/vq-f4.zip

**Comment by yunfei920406** [comment]
> The pre-trained VQGAN models provided by LDM can be directly used for all tasks. https://github.com/CompVis/latent-diffusion#bibtex

Do you mean that I can train my any datasets with the checkpoint file you provided in the above link.

**Comment by yunfei920406** [comment]
> > > The pre-trained VQGAN models provided by LDM can be directly used for all tasks. https://github.com/CompVis/latent-diffusion#bibtex
> > 
> > 
> > Do you mean that I can train my any datasets with the checkpoint file you provided in the above link.
> 
> yes. or you can finetune on your own dataset based on this checkpoint

Thanks for your reply
